//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App12COFFEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIChat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIChat()
        {
            this.AITinNhans = new HashSet<AITinNhan>();
        }
    
        public int MaChat { get; set; }
        public int MaND { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITinNhan> AITinNhans { get; set; }
    }
}
