//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App12COFFEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITinNhan
    {
        public int MaTinNhan { get; set; }
        public int MaChat { get; set; }
        public string LoaiNguoiGui { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> DaDoc { get; set; }
        public Nullable<int> Tokens { get; set; }
    
        public virtual AIChat AIChat { get; set; }
    }
}
