//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App12COFFEE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MaDG { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaND { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
